<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class LocalCustomer
 *
 * @property int $id
 * @property int|null $local_id
 * @property string|null $firstname
 * @property string|null $lastname
 * @property string|null $email
 * @property string|null $address
 * @property string|null $phone_number
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * @package App\Models
 */
class LocalCustomer extends Model
{
    protected $table = 'local_customers';

    protected $casts = [
        'local_id' => 'int'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($model){
            self::linkUserWithLocalData($model);
        });

        self::updated(function($model){
            self::linkUserWithLocalData($model);
        });
    }


    /**
     * @param LocalCustomer $model
     * @return void
     */
    public static function linkUserWithLocalData(self $model) : void
    {
        $superMarketUsers = SupermarketUser::where('phone', $model->phone)->get();
        if($superMarketUsers->count() > 0){
            foreach($superMarketUsers as $superMarketUser){
                $superMarketUser->local_customer_id = $model->id;
                $superMarketUser->save();
            }
        }


        $wholesalesUsers = WholesalesUser::where('phone', $model->phone)->get();
        if($wholesalesUsers->count() > 0){
            foreach($wholesalesUsers as $wholesalesUser){
                $wholesalesUser->local_customer_id = $model->id;
                $wholesalesUser->save();
            }
        }
    }

    protected $fillable = [
        'local_id',
        'firstname',
        'lastname',
        'email',
        'address',
        'phone_number'
    ];

}
