<?php

/**
 * Created by Reliese Model.
 */

namespace App\Models;

use App\Classes\Settings;
use App\Traits\ModelFilterTraits;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class NewStockArrival
 *
 * @property int $id
 * @property int $stock_id
 * @property int $app_id
 * @property int $quantity
 * @property Carbon $arrival_date
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * @property App $app
 * @property Stock $stock
 *
 * @package App\Models
 */
class NewStockArrival extends Model
{
    use ModelFilterTraits;

	protected $table = 'new_stock_arrivals';

	protected $casts = [
		'stock_id' => 'int',
		'app_id' => 'int',
		'quantity' => 'int',
		'arrival_date' => 'datetime'
	];

	protected $fillable = [
		'stock_id',
		'app_id',
		'quantity',
		'arrival_date'
	];


    protected $with = ['app', 'stock'];

	public function app()
	{
		return $this->belongsTo(App::class);
	}

	public function stock()
	{
		return $this->belongsTo(Stock::class, 'stock_id');
	}


    /**
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function(NewStockArrival $model){
            $model->triggerNewArrivalCount();
        });
    }





}
