<?php

namespace App\Enums\Permission;

enum Settings
{
    const CONFIG = [
        'name' => 'Settings',
        'label' => 'Settings',
        'description' => 'Manage Settings Module',
        'status' => '1',
        'visibility' => '1',
        'order' => '1',
        'icon' => 'icon',
        'app_id' => [2,3]
    ];

    const PERMISSION = [
        [
            "id" => "1",
            "name" => "backend.admin.settings.system_settings",
            "module_id" => "1",
            "label" => "System Settings",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "2",
            "name" => "backend.admin.settings.system_settings.update",
            "module_id" => "1",
            "label" => "Update System Settings",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "3",
            "name" => "backend.admin.settings.manufacturer",
            "module_id" => "1",
            "label" => "Manufacturers",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "4",
            "name" => "backend.admin.settings.manufacturer.destroy",
            "module_id" => "1",
            "label" => "Destroy Manufacturer",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "5",
            "name" => "backend.admin.settings.manufacturer.create",
            "module_id" => "1",
            "label" => "Create Manufacturer",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "6",
            "name" => "backend.admin.settings.manufacturer.toggle",
            "module_id" => "1",
            "label" => "Toggle Manufacturer",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "7",
            "name" => "backend.admin.settings.manufacturer.edit",
            "module_id" => "1",
            "label" => "Edit Manufacturer",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "8",
            "name" => "backend.admin.settings.classification",
            "module_id" => "1",
            "label" => "Classifications",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "9",
            "name" => "backend.admin.settings.classification.destroy",
            "module_id" => "1",
            "label" => "Destroy Classification",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "10",
            "name" => "backend.admin.settings.classification.create",
            "module_id" => "1",
            "label" => "Create Classification",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "11",
            "name" => "backend.admin.settings.classification.toggle",
            "module_id" => "1",
            "label" => "Toggle Classification",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "12",
            "name" => "backend.admin.settings.classification.edit",
            "module_id" => "1",
            "label" => "Edit Classification",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "13",
            "name" => "backend.admin.settings.product_category",
            "module_id" => "1",
            "label" => "Product Categories",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "14",
            "name" => "backend.admin.settings.product_category.destroy",
            "module_id" => "1",
            "label" => "Destroy Product Category",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "15",
            "name" => "backend.admin.settings.product_category.create",
            "module_id" => "1",
            "label" => "Create Product Category",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "16",
            "name" => "backend.admin.settings.product_category.toggle",
            "module_id" => "1",
            "label" => "Toggle Product Category",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "17",
            "name" => "backend.admin.settings.product_category.edit",
            "module_id" => "1",
            "label" => "Edit Product Category",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "18",
            "name" => "backend.admin.settings.product_group",
            "module_id" => "1",
            "label" => "Product Groups",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "19",
            "name" => "backend.admin.settings.product_group.destroy",
            "module_id" => "1",
            "label" => "Destroy Product Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "20",
            "name" => "backend.admin.settings.product_group.create",
            "module_id" => "1",
            "label" => "Create Product Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "21",
            "name" => "backend.admin.settings.product_group.toggle",
            "module_id" => "1",
            "label" => "Toggle Product Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "22",
            "name" => "backend.admin.settings.product_group.edit",
            "module_id" => "1",
            "label" => "Edit Product Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "23",
            "name" => "backend.admin.settings.bank_account",
            "module_id" => "1",
            "label" => "Bank Accounts",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "24",
            "name" => "backend.admin.settings.bank_account.destroy",
            "module_id" => "1",
            "label" => "Destroy Bank Account",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "25",
            "name" => "backend.admin.settings.bank_account.create",
            "module_id" => "1",
            "label" => "Create Bank Account",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "26",
            "name" => "backend.admin.settings.bank_account.toggle",
            "module_id" => "1",
            "label" => "Toggle Bank Account",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "27",
            "name" => "backend.admin.settings.bank_account.edit",
            "module_id" => "1",
            "label" => "Edit Bank Account",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "28",
            "name" => "backend.admin.settings.order_total",
            "module_id" => "1",
            "label" => "Order Totals",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "29",
            "name" => "backend.admin.settings.order_total.destroy",
            "module_id" => "1",
            "label" => "Destroy Order Total",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "30",
            "name" => "backend.admin.settings.order_total.create",
            "module_id" => "1",
            "label" => "Create Order Total",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "31",
            "name" => "backend.admin.settings.order_total.toggle",
            "module_id" => "1",
            "label" => "Toggle Order Total",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "32",
            "name" => "backend.admin.settings.order_total.edit",
            "module_id" => "1",
            "label" => "Edit Order Total",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "33",
            "name" => "backend.admin.settings.customer_group",
            "module_id" => "1",
            "label" => "Customer Groups",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "34",
            "name" => "backend.admin.settings.customer_group.destroy",
            "module_id" => "1",
            "label" => "Destroy Customer Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "35",
            "name" => "backend.admin.settings.customer_group.create",
            "module_id" => "1",
            "label" => "Create Customer Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "36",
            "name" => "backend.admin.settings.customer_group.toggle",
            "module_id" => "1",
            "label" => "Toggle Customer Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:15",
            "updated_at" => "2024-03-26 11:54:15",
        ],
        [
            "id" => "37",
            "name" => "backend.admin.settings.customer_group.edit",
            "module_id" => "1",
            "label" => "Edit Customer Group",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "38",
            "name" => "backend.admin.settings.customer_type",
            "module_id" => "1",
            "label" => "Customer Types",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "39",
            "name" => "backend.admin.settings.customer_type.destroy",
            "module_id" => "1",
            "label" => "Destroy Customer Type",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "40",
            "name" => "backend.admin.settings.customer_type.create",
            "module_id" => "1",
            "label" => "Create Customer Type",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "41",
            "name" => "backend.admin.settings.customer_type.toggle",
            "module_id" => "1",
            "label" => "Toggle Customer Type",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "42",
            "name" => "backend.admin.settings.customer_type.edit",
            "module_id" => "1",
            "label" => "Edit Customer Type",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "43",
            "name" => "backend.admin.settings.local_government",
            "module_id" => "1",
            "label" => "Local Governments",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "44",
            "name" => "backend.admin.settings.local_government.destroy",
            "module_id" => "1",
            "label" => "Destroy Local Government",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "45",
            "name" => "backend.admin.settings.local_government.create",
            "module_id" => "1",
            "label" => "Create Local Government",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "46",
            "name" => "backend.admin.settings.local_government.toggle",
            "module_id" => "1",
            "label" => "Toggle Local Government",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "47",
            "name" => "backend.admin.settings.local_government.edit",
            "module_id" => "1",
            "label" => "Edit Local Government",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "48",
            "name" => "backend.admin.settings.address_and_town.show",
            "module_id" => "1",
            "label" => "Show Address And Town",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "49",
            "name" => "backend.admin.settings.address_and_town.destroy",
            "module_id" => "1",
            "label" => "Destroy Address And Town",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "50",
            "name" => "backend.admin.settings.address_and_town.create",
            "module_id" => "1",
            "label" => "Create Address And Town",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "51",
            "name" => "backend.admin.settings.address_and_town.toggle",
            "module_id" => "1",
            "label" => "Toggle Address And Town",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "52",
            "name" => "backend.admin.settings.address_and_town.edit",
            "module_id" => "1",
            "label" => "Edit Address And Town",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "53",
            "name" => "backend.admin.settings.image_slider",
            "module_id" => "1",
            "label" => "Image Sliders",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "54",
            "name" => "backend.admin.settings.image_slider.destroy",
            "module_id" => "1",
            "label" => "Destroy Image Slider",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "55",
            "name" => "backend.admin.settings.image_slider.create",
            "module_id" => "1",
            "label" => "Create Image Slider",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "56",
            "name" => "backend.admin.settings.image_slider.toggle",
            "module_id" => "1",
            "label" => "Toggle Image Slider",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "57",
            "name" => "backend.admin.settings.image_slider.edit",
            "module_id" => "1",
            "label" => "Edit Image Slider",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "58",
            "name" => "backend.admin.settings.product_banner",
            "module_id" => "1",
            "label" => "Product Banners",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "59",
            "name" => "backend.admin.settings.product_banner.destroy",
            "module_id" => "1",
            "label" => "Destroy Product Banner",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "60",
            "name" => "backend.admin.settings.product_banner.create",
            "module_id" => "1",
            "label" => "Create Product Banner",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "61",
            "name" => "backend.admin.settings.product_banner.toggle",
            "module_id" => "1",
            "label" => "Toggle Product Banner",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "62",
            "name" => "backend.admin.settings.product_banner.edit",
            "module_id" => "1",
            "label" => "Edit Product Banner",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "63",
            "name" => "backend.admin.settings.image_gallery",
            "module_id" => "1",
            "label" => "Image Galleries",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "64",
            "name" => "backend.admin.settings.image_gallery.destroy",
            "module_id" => "1",
            "label" => "Destroy Image Gallery",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "65",
            "name" => "backend.admin.settings.image_gallery.create",
            "module_id" => "1",
            "label" => "Create Image Gallery",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "66",
            "name" => "backend.admin.settings.image_gallery.toggle",
            "module_id" => "1",
            "label" => "Toggle Image Gallery",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "67",
            "name" => "backend.admin.settings.image_gallery.edit",
            "module_id" => "1",
            "label" => "Edit Image Gallery",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "68",
            "name" => "backend.admin.settings.town_and_distance",
            "module_id" => "1",
            "label" => "Towns And Distances",
            "visibility" => "1",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "69",
            "name" => "backend.admin.settings.town_and_distance.destroy",
            "module_id" => "1",
            "label" => "Destroy Town And Distance",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "70",
            "name" => "backend.admin.settings.town_and_distance.create",
            "module_id" => "1",
            "label" => "Create Town And Distance",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "72",
            "name" => "backend.admin.settings.town_and_distance.edit",
            "module_id" => "1",
            "label" => "Edit Town And Distance",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "id" => "73",
            "name" => "backend.admin.settings.town_and_distance.upload",
            "module_id" => "1",
            "label" => "Upload Town & Distance",
            "visibility" => "0",
            "guard_name" => "web",
            "created_at" => "2024-03-26 11:54:16",
            "updated_at" => "2024-03-26 11:54:16",
        ],
        [
            "name" => "backend.admin.settings.payment_methods",
            "module_id" => "1",
            "label" => "Payment Methods",
            "visibility" => "1",
            "guard_name" => "web",
        ],
        [
            "name" => "backend.admin.settings.payment_methods.toggle",
            "module_id" => "1",
            "label" => "Toggle Payment Methods",
            "visibility" => "0",
            "guard_name" => "web",
        ],
        [
            "name" => "backend.admin.settings.payment_methods.settings",
            "module_id" => "1",
            "label" => "Payment Method Settings",
            "visibility" => "0",
            "guard_name" => "web",
        ],
        [
            "name" => "backend.admin.settings.delivery_methods",
            "module_id" => "1",
            "label" => "Delivery Methods",
            "visibility" => "1",
            "guard_name" => "web",
        ],
        [
            "name" => "backend.admin.settings.delivery_methods.toggle",
            "module_id" => "1",
            "label" => "Toggle Delivery Methods",
            "visibility" => "0",
            "guard_name" => "web",
        ],
        [
            "name" => "backend.admin.settings.delivery_methods.settings",
            "module_id" => "1",
            "label" => "Delivery Method Settings",
            "visibility" => "0",
            "guard_name" => "web",
        ]

    ];





}
