<?php

namespace App\Enums;

enum KafkaAction
{
    const PROCESS_ORDER = "PROCESS_ORDER";
    const PACKED_ORDER = "PACKED_ORDER";
    const TESTING_KAFKA = "TESTING_KAFKA";

    const CREATE_BRAND = "CREATE_BRAND";
    const UPDATE_BRAND = "UPDATE_BRAND";
    const CREATE_CATEGORY = "CREATE_CATEGORY";
    const UPDATE_CATEGORY = "UPDATE_CATEGORY";
    const CREATE_CLASSIFICATION = "CREATE_CLASSIFICATION";
    const UPDATE_CLASSIFICATION = "UPDATE_CLASSIFICATION";

    const CREATE_CUSTOMER = "CREATE_CUSTOMER";
    const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

    const CREATE_MANUFACTURER = "CREATE_MANUFACTURER";
    const UPDATE_MANUFACTURER = "UPDATE_MANUFACTURER";
    const NEW_ARRIVAL = "NEW_ARRIVAL";

    const CREATE_STOCK_GROUP = "CREATE_STOCK_GROUP";
    const UPDATE_STOCK_GROUP = "UPDATE_STOCK_GROUP";

    const CREATE_STOCK = "CREATE_STOCK";
    const UPDATE_STOCK = "UPDATE_STOCK";
    const PROCESS_ORDER_ERROR = "PROCESS_ORDER_ERROR";
    const ORDER_PROCESSED_UPDATE = "ORDER_PROCESSED_UPDATE";


}
